import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Viajes from '@/components/Viajes'
import destino from '@/datos/datos'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1 id='titulo'>Los viajes de Sergio y Javier</h1>
            {
              destino.map(n=>(<Link href="Viaje_concreto"><Viajes descripcion={n.descripcion} imagen={n.imagen_corta} titulo={n.titulo}></Viajes></Link>))
            }
        </div>
      </main>
    </>
  )
}
