
import Viaje_concreto from "@/components/Viaje_concreto";
import Head from "next/head"

const primercurso=()=>{
    return(
        <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
            <div>
           < Viaje_concreto imagen={"https://images.pexels.com/photos/670261/pexels-photo-670261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"} titulo={"Madrid"} descripcion={"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione nesciunt nemo libero repudiandae quisquam nulla cum repellat recusandae aut voluptatibus. Minima earum ad ipsum repellendus voluptatum quas, asperiores quidem libero? asjdkshkjdhkasj akjsdkjsadhkjashdkjhsadkjhsa kjasdhkjsdh"}></Viaje_concreto>
            </div>
      </main>
        </>
    )
}
export default primercurso;
